.github/workflows/branch-name-validation.yml, .github/workflows/pr-title-validation.yml, src/main/java/com/GP/GP/roles/admin/controller/AdminController.java, src/main/java/com/GP/GP/roles/admin/service/contracts/UniversityService.java, src/main/java/com/GP/GP/roles/admin/service/impl/UniversityServiceImpl.java
=> feat: create [ get all universities ] API with spring boot

src/main/java/com/GP/GP/roles/user/controller/UserController.java, src/main/java/com/GP/GP/roles/user/dto/AdmissionRequestDTO.java, src/main/java/com/GP/GP/roles/user/mapper/AdmissionRequestMapper.java, src/main/java/com/GP/GP/roles/user/service/contracts/AdmissionRequestService.java, src/main/java/com/GP/GP/roles/user/service/impl/AdmissionRequestImpl.java
=> refactor: use base response in endpoints

src/main/java/com/GP/GP/roles/admin/controller/AdminController.java, src/main/java/com/GP/GP/roles/admin/models/mapper/AdminMapper.java, src/main/java/com/GP/GP/roles/admin/service/contracts/UniversityService.java, src/main/java/com/GP/GP/roles/admin/service/impl/GuideLineServiceImpl.java, src/main/java/com/GP/GP/roles/admin/service/impl/UniversityServiceImpl.java
=> feat: Add Delete University and Delete All Universities Endpoints

src/main/java/com/GP/GP/entities/AdmissionRequest.java, src/main/java/com/GP/GP/roles/user/mapper/AdmissionRequestMapper.java
=> refactor: use Builder annotation to AdmissionRequest entity

src/main/java/com/GP/GP/entities/AdmissionRequest.java, src/main/java/com/GP/GP/repository/AdmissionRequestRepository.java, src/main/java/com/GP/GP/roles/user/controller/AdmissionRequestController.java, src/main/java/com/GP/GP/roles/user/service/contracts/AdmissionRequestService.java, src/main/java/com/GP/GP/roles/user/service/impl/AdmissionRequestImpl.java
**- rename user controller class to admission request controller**
**- change routes in admission request controller class** 
**- add get all admission requests in service and controller**
**- add get admission request by user id in service and controller and add new Query in ar repository**
**-add update admission status in service and controller**
=> feat: add get all admission requests service and controller

src/main/java/com/GP/GP/entities/Complaint.java, src/main/java/com/GP/GP/repository/ComplaintRepository.java, src/main/java/com/GP/GP/roles/user/controller/ComplaintController.java, src/main/java/com/GP/GP/roles/user/model/mapper/ComplaintMapper.java, src/main/java/com/GP/GP/roles/user/model/request/ComplaintRequestDTO.java, src/main/java/com/GP/GP/roles/user/model/response/ComplaintResponseDTO.java, src/main/java/com/GP/GP/roles/user/service/contracts/ComplaintService.java, src/main/java/com/GP/GP/roles/user/service/impl/ComplaintServiceImpl.java
- Create a new complaint (User)
- Get all complaints (Admin)
- Get a complaint by ID (Admin)
- Update a complaint by ID (User)
- Delete a complaint by ID (Admin)
- Get all complaints by a specific user (Admin)
=> feat: add complaint end points 

src/main/java/com/GP/GP/entities/Building.java, src/main/java/com/GP/GP/entities/Room.java, src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/utill/Enums.java
- add Enum of building type for male buildings and female buildings 
- add time stamps fields  in rooms and buildings.
- get ensure of the relationship:
1. Building ⟶ Rooms (One-to-Many) 
2. Room ⟶ Students "Users" (One-to-Many, instead of Many-to-Many) 
3. User belongs to only one Room at a time 
4. Cascade only for PERSIST (no unintentional deletions)
=> refactor: rooms and building entities. 

src/main/java/com/GP/GP/entities/Penalty.java, src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/repository/PenaltyRepository.java, src/main/java/com/GP/GP/roles/admin/controller/PenaltyController.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/PenaltyDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/PenaltyResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/mapper/PenaltyMapper.java, src/main/java/com/GP/GP/roles/admin/service/contracts/PenaltyService.java, src/main/java/com/GP/GP/roles/admin/service/impl/PenaltyServiceImpl.java
- **Create Penalty**
- **get penalty by id**
- **get all penalties**
- **get penalties for specific user**
- **delete penalty**
=> feat: add penality feature 

src/main/java/com/GP/GP/config/WebConfig.java, src/main/java/com/GP/GP/entities/User.java
=> refactor: faculty length and allowed hosts  

src/main/java/com/GP/GP/roles/user/service/impl/UserServiceImpl.java
=> refactor: update Admission Request Statues in user service imple.

src/main/java/com/GP/GP/roles/user/controller/ComplaintController.java, src/main/java/com/GP/GP/roles/user/service/impl/ComplaintServiceImpl.java
=> refactor: add a new end point for user to get his own complaints

src/main/java/com/GP/GP/entities/ApplicationDeadline.java, src/main/java/com/GP/GP/entities/ApplicationGuidelineAndApproval.java, src/main/java/com/GP/GP/entities/Building.java, src/main/java/com/GP/GP/entities/HousingFee.java, src/main/java/com/GP/GP/entities/University.java
- use the @JsonManagedReference & @JsonBackReference annotations to prevent recursion issues while keeping the data in JSON
=> refactor: use @JsonManagedReferenc and @JsonBackReference 

src/main/java/com/GP/GP/entities/Building.java, src/main/java/com/GP/GP/entities/Room.java, src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/repository/BuildingRepository.java, src/main/java/com/GP/GP/repository/RoomRepository.java, src/main/java/com/GP/GP/roles/Auth/models/response/RegisterResponseDTO.java, src/main/java/com/GP/GP/roles/Auth/service/AuthenticationService.java, src/main/java/com/GP/GP/roles/admin/controller/RoomController.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/RoomAssignmentRequestDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/RoomAssignmentResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/mapper/RoomAssignmentMapper.java, src/main/java/com/GP/GP/roles/admin/service/contracts/RoomAssignmentService.java, src/main/java/com/GP/GP/roles/admin/service/contracts/RoomService.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomAssignmentServiceImpl.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomServiceImpl.java
- get specific room :
- check room availability by room type Single, double or dorm:
this API filters rooms based on the room type, current occupancy, and status
- create room Assignment dto for  response 
- and for request
- room assignment service implementation and its criteria 
1. Get student by ID
2. Check if already assigned to a room
3. Check if student is accepted
4. Get building type from gender
5. Find available room
6. Assign room to student
7. Return response DTO
- remove student from a room
=> feat: add get available rooms and get room by id and make room assignment feature 

src/main/java/com/GP/GP/repository/UserRepository.java, src/main/java/com/GP/GP/roles/admin/controller/RoomController.java, src/main/java/com/GP/GP/roles/admin/service/contracts/RoomAssignmentService.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomAssignmentServiceImpl.java
=> feat: add assign a student to specific room

src/main/java/com/GP/GP/roles/admin/controller/AdmissionRequestExportController.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/AdmissionRequestExportDtO.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/AdmissionRequestFilterDTO.java, src/main/java/com/GP/GP/roles/admin/models/mapper/AdmissionRequestExportMapper.java, src/main/java/com/GP/GP/roles/admin/service/contracts/AdmissionRequestExportService.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestExportServiceImpl.java, src/main/resources/application.properties
export admission request after applying filters
like:
private Enums.AdmissionRequestStatues status;
private Enums.Gender gender;
private String universityName;
private String faculty;
private String  level;
private Boolean specialNeeds;
private LocalDateTime startDate;
private LocalDateTime endDate;
private String studentType;
=> feat: create export admission requests to Excel sheet and filters 

src/main/java/com/GP/GP/roles/admin/controller/AdmissionRequestExportController.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/AdmissionRequestFilterDTO.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestExportServiceImpl.java, src/main/java/com/GP/GP/roles/user/controller/UserController.java, src/main/java/com/GP/GP/roles/user/service/impl/UserServiceImpl.java
change get ar by user id URL to be admin/ view
fix get ar by id for users to retrieve only ar for authorized user
=> fix: get admission status by id for user and viewer admin

src/main/java/com/GP/GP/repository/UserRepository.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestExportServiceImpl.java
create a JPA method to filter admission requests with only user role
=> fix: apply filters only with role users

src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/roles/admin/controller/AdmissionRequestExportController.java, src/main/java/com/GP/GP/roles/admin/controller/AdmissionRequestUploadController.java, src/main/java/com/GP/GP/roles/admin/service/contracts/AdmissionRequestExportService.java, src/main/java/com/GP/GP/roles/admin/service/contracts/AdmissionRequestUploadService.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestExportServiceImpl.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestUploadServiceImpl.java, src/main/java/com/GP/GP/roles/user/model/mapper/UserMapper.java, src/main/java/com/GP/GP/roles/user/model/response/UpdatedUserResponseDTO.java
- create an Excel sheet sample to be downloaded via endpoint :
- create endpoint to upload Excel sheet sample and update the database 
- create endpoint to check Excel sheet extension .xls or xlsx
- add security check and notes to get all ar endpoint
=> feat: create upload endpoint 

src/main/java/com/GP/GP/roles/admin/controller/AdmissionRequestExportController.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/AdmissionRequestFilterDTO.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestExportServiceImpl.java, src/main/java/com/GP/GP/roles/user/model/mapper/UserMapper.java, src/main/java/com/GP/GP/roles/user/model/response/UpdatedUserResponseDTO.java
=> feat: add penalty count to ar response and create new filter get student with/without penalities

src/main/java/com/GP/GP/entities/Building.java, src/main/java/com/GP/GP/entities/Room.java, src/main/java/com/GP/GP/repository/RoomRepository.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/BuildingRequestDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/RoomRequestDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/BuildingResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/BuildingSummaryResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/RoomResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/mapper/BuildingMapper.java, src/main/java/com/GP/GP/roles/admin/models/mapper/RoomMapper.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomAssignmentServiceImpl.java
1. Building
floorsCount, wingsCount
3.Room
floorNumber, wing, bedCount, occupiedBeds
4. add Transactional annotation for assignStudentToRoom 
5. add Lock annotation with PESSIMISTIC_WRITE MODE in room repository  for findAvailableRoomsByBuildingTypeAndRoomType
6. instead of using full building entity in response  create building summary DTo 
I find out that Ali has create one for user already so I need to use it instead or keep it I don't know 
and thats it 
7.  also add AND r.occupiedBeds < r.bedCount this check in findAvailableRoomsByBuildingAndRoomType
=> feat: enhance accomodations entities 

src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/roles/admin/controller/RoomAssignmentExcelController.java, src/main/java/com/GP/GP/roles/admin/models/dto/response/RoomAssignmentResponseDTO.java, src/main/java/com/GP/GP/roles/admin/models/mapper/RoomAssignmentMapper.java, src/main/java/com/GP/GP/roles/admin/service/contracts/RoomAssignmentExcelService.java, src/main/java/com/GP/GP/roles/admin/service/impl/AdmissionRequestUploadServiceImpl.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomAssignmentExcelServiceImpl.java, src/main/java/com/GP/GP/roles/admin/service/impl/RoomAssignmentServiceImpl.java, src/main/java/com/GP/GP/roles/user/model/mapper/StudentMapper.java, src/main/java/com/GP/GP/roles/user/model/mapper/StudentPriorityMapper.java, src/main/java/com/GP/GP/roles/user/model/mapper/UserMapper.java, src/main/java/com/GP/GP/roles/user/model/response/UpdatedUserResponseDTO.java
1. change the note to →  securityCheckNotes
2. add → AdmissionRequestStatusNotes 
3. in uploading security check template no need to put the whole Enum anymore just :
0 → ACCEPTED
1 → REJECTED
2→ PENDING
=> feat: create upload and download Excel sheet for housing 

src/main/java/com/GP/GP/roles/Auth/service/AuthenticationService.java, src/main/java/com/GP/GP/roles/admin/models/dto/request/AdmissionStatusNotesDTO.java, src/main/java/com/GP/GP/roles/user/controller/UserController.java, src/main/java/com/GP/GP/roles/user/service/contracts/AdmissionRequestService.java, src/main/java/com/GP/GP/roles/user/service/impl/UserServiceImpl.java
1. add admission request rejection notes 
2. edit the register to set default msg in security check notes and status 
3. removed a bothering comment from ar service file
=> feat: add rejection notes 

src/main/java/com/GP/GP/config/SecurityConfig.java, src/main/java/com/GP/GP/entities/User.java, src/main/java/com/GP/GP/filter/JwtAuthenticationFilter.java, src/main/java/com/GP/GP/repository/PrivilegeRepository.java, src/main/java/com/GP/GP/roles/Auth/controller/PrivilegeController.java, src/main/java/com/GP/GP/roles/Auth/models/mapper/PrivilegeMapper.java, src/main/java/com/GP/GP/roles/Auth/models/request/PrivilegesAssignmentRequestDTO.java, src/main/java/com/GP/GP/roles/Auth/models/response/PrivilegeResponseDTO.java, src/main/java/com/GP/GP/roles/Auth/service/PrivilegeService.java, src/main/java/com/GP/GP/roles/admin/controller/RoomController.java, src/main/java/com/GP/GP/security/AccessChecker.java, src/main/java/com/GP/GP/security/Privilege.java, src/main/java/com/GP/GP/security/UserDetailsServiceImp.java
=> feat: create a fine grain user privileges

src/main/java/com/GP/GP/entities/Appeal.java, src/main/java/com/GP/GP/repository/AppealRepository.java, src/main/java/com/GP/GP/roles/user/controller/AppealController.java, src/main/java/com/GP/GP/roles/user/controller/ComplaintController.java, src/main/java/com/GP/GP/roles/user/controller/UserController.java, src/main/java/com/GP/GP/roles/user/model/mapper/AppealMapper.java, src/main/java/com/GP/GP/roles/user/model/request/AppealRequestDTO.java, src/main/java/com/GP/GP/roles/user/model/response/AppealResponseDTO.java, src/main/java/com/GP/GP/roles/user/service/contracts/AppealService.java, src/main/java/com/GP/GP/roles/user/service/impl/AppealServiceImpl.java
and add to user controller and complaint controller
=> feat: appeal service
